version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data